gradle.properties
inappmessaging/build.gradle
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/Message.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/CampaignData.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListener.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/InvalidTestMessage.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/ValidTestMessage.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/MessageMixerResponseSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt

Solution no. 2 for issue https://github.com/rakutentech/ios-inappmessaging/issues/10
I couldn't get some unit tests to work. I'd appreciate any help on that because I've used all my ideas...
Tested on Android simulator with real campaign data.
https://github.com/rakutentech/ios-inappmessaging/issues/10
SDKCF-2871

feat: handle context as a part of campaign's title and add validation callback before displaying the message (SDKCF-2870)

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/MessageMixerResponseSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt

When campaign was rejected it was still marked as ready to display so when `prepareNextMessage()` was called after `onVerifyContext()` returned false the repository kept returning the same message over and over creating a cycle.
Rejected campaigns ara now stored in a list.

fix: fix cyclical call when onVerifyContext returned false, update user guide

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt

subtract() method doesn't modify existing list - it's returning new object (a Set) instead.
It was easier to use a condition instead of subtracting 2 lists.

fix: fix messageList.subtract() call

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt

This prevents from stacking campaigns (events) when campaign's context was rejected and later accepted.

fix: update LocalDisplayedMessageRepository after rejecting campaign's context

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt

without that fix, MessageReadinessManager will keep returning the same message

fix: update ReadyForDisplayMessageRepository after rejecting campaign's context

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManagerSpec.kt
test/src/main/java/com/rakuten/test/MainActivityFragment.kt
test/src/main/res/layout/fragment_main.xml

This new API is for programmatically closing campaigns without user interaction.

feat: [SDKCF-3199] add close campaign API and refactor some test codes

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt

This is an expected behavior but was not implemented from the original code (in Java)

feat: [SDKCF-3219] add removing of displayed message when app unregister activity

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/Message.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/MessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/CampaignData.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/InvalidTestMessage.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/ValidTestMessage.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/MessageMixerResponseSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtilSpec.kt

add closed counter to the `CampaignData` to consider in the number of events to trigger.

feat: [SDKCF-3266] add clearing for campaign to display queue

---

.circleci/config.yml
README.md
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
inappmessaging/USERGUIDE.md
inappmessaging/build.gradle
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/Impression.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/UserIdentifier.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/rat/RatAttribute.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/rat/RatImpression.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/ConfigRequest.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/DisplayPermissionRequest.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/PingRequest.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnable.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageFullScreenView.kt

because of Jcenter/bintray shutdown, publishing is done now to maven central
* class changes are only to removed findbugs annotations

ci: update config for publishing to maven central instead of bintray

---

inappmessaging/build.gradle
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/Message.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/CampaignData.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/SharePreferencesUtil.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/BaseTest.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/TestKeyStore.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/InvalidTestMessage.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/ValidTestMessage.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManagerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManagerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt

used encrypted shared preference (unique for each user) to save all the campaign and event repositories

feat: make local respositories persistent per user to move opt-out and max impression handling solely on SDK

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt

fix: move restoring of cached data before check if initial launch to prevent multiple app launch events

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/MessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt

if `onVerifyContext` returns false, the times closed for campaign is increased to have the correct count of required number of events trigger without incrementing the campaign's impression

fix: add cache handling for onVerifyContext and fix app launch campaign display behavior

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt

When app is killed while a campaign is displayed, all triggered events are still cached. On next app launch, the campaign will still be displayed since all required events were still triggered from cached data.
To handle this behavior, a new counter is introduced to know the number of times the campaign is closed due to app being killed.

fix: add handling for closed campaign when app is killed

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManager.kt

When a persistent event is triggered before a non-persistent event while the user info is updated, the ping request was not triggered.
Added handling to make sure that ping request is triggered.

fix: added handling for ping request not executed if a persistent event was triggered first

---

inappmessaging/USERGUIDE.md

- fix documentation format for Troubleshooting
- update target SDK and compile SDK version to be 30

docs: fix documentation format for Troubleshooting

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManager.kt

To avoid `ConcurrentModificationException`, changed `LinkedHashMap` to `ConcurrentHashMap`.
For other cache data (non-map), add synchronization to be thread-safe.

fix: add synchronization for non-map cache data, and change map to concurrent map

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtilSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListenerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigSchedulerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationSchedulerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt

When config is disabled (possibly because of low rollout percentage), logging of events and displaying/removing of campaigns are also disabled.

feat: add disabled config handling for register/unregister activity, and logging events

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt

Because of timing issue (edge case), it is possible that the user info is not yet updated when moving temp events to persistent data.
Temp events were used for logged events while config API request is still in progress.

fix: add user info update when moving temp data to persistent cache when config is enabled

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepositorySpec.kt

Fix issue where old triggered events in cache are still used for new campaigns.

refactor: [SDKCF-4002] delete old events used to trigger new campaigns

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepositorySpec.kt
test/src/main/java/com/rakuten/test/MainActivityFragment.kt
test/src/main/res/layout/fragment_main.xml
test/src/main/res/values/strings.xml

fix: [SDKCF 4002] old events can still be used to trigger new campaigns

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/appevents/BaseEvent.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/appevents/Event.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManager.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepositorySpec.kt

Since old events are cleared after ping request, logged events that trigger session update will be cleared.
To avoid this, a flag is added for events which will prevent the event to be cleared

fix: add flag to event when user info was updated (session update) to avoid getting cleared

---

inappmessaging/src/main/res/layout/message_scrollview.xml

`textAlignment` alone is not working when `materials` dependency is included in app

fix: add gravity center for headers

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/appevents/BaseEvent.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/appevents/Event.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManager.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepositorySpec.kt

added flag to handle logging of events while ping request is still in progress
* avoid clearing "old" events which were triggered while config request or ping request is ongoing

bug: add flag to handle log event timing issue during ping request

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt

fix: add display of next campaign when queue is not cleared

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/DisplaySettings.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListener.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationScheduler.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/MessageMixerResponseSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListenerSpec.kt

Add delay before displaying next campaign (sync with iOS)

improvement: add delay between campaign display

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt

feat: [SDKCF-4468] remove deprecated updateSession API

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/EventTrackerHelper.kt

Update the `ClassNotFoundException` to info exception, to avoid showing error logs every time an event is sent when the host app doesn't implement Analytics SDK dependencies.

improvement: update ClassNotFoundException log type in analytics module 

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/CacheUtil.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/CacheUtilSpec.kt

Update Picasso memory cache config to avoid OutOfMemory exception.
[SDKCF-4661]

fix: update Picasso memory cache config

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ImageUtilSpec.kt

[SDKCF-4677] Remove picasso cache indicator and loging.

refactor: remove picasso cache indicator

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnable.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ImageUtil.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageFullScreenView.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageModalView.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageSlideUpView.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageView.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ImageUtilSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/BaseViewSpec.kt

Bitmal retrieval causes the OOM in low memory device.
To avoid this, the SDK will use normal fetch and use device width for resizing.

fix: change bitmap retrieval to normal picasso fetch to improve performance (SDKCF-4684)

---

bitrise.yml
build.gradle

Current sonarqube instance requires analysis to build in Java 11

ci: set java version to 11 when running sonarqube

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnable.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListener.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManagerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnableSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListenerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipViewSpec.kt

auto-disappear is the timer for automatically removing tooltip without tapping the close button.

fix: update behavior for auto-disappear parameter

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtil.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipView.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtilSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipViewSpec.kt

image in tooltip layout is in disrupted when part of the campaign is over the right or bottom edge of the device

fix: add handling for tooltip that are over the edge of device

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
inappmessaging/src/main/res/values/colors.xml
inappmessaging/src/main/res/values/dimens.xml
inappmessaging/src/main/res/values/styles.xml
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/BaseViewSpec.kt

Action button should have a border when campaign body has the same background color.
SDKCF-4859

improve: draw button's border if it has the same bg color as campaign (SDKCF-4859)

---

inappmessaging/src/main/res/layout/in_app_message_slide_up.xml
inappmessaging/src/main/res/values/dimens.xml

fix: Slide up message: fix spacing when close button is hidden (SDKCF-5002)

---

inappmessaging/src/main/res/values/dimens.xml

fix: use wider stroke width for button border (SDKCF-4859)

---

bitrise.yml

fix: add missing DependencyCheck job to build and test workflow

---

build.gradle
dependency-check.gradle
sonar.gradle

- Sonarqube doesn't display the report when the path to the generated report is customized -> Used the default  path
- Changed the type of CVSS score to float to be able to config more accurate value.
- Bumped Dependency check to v7.1.0.1

fix: Sonarqube Dependencycheck report display

---

Dangerfile
bitrise.yml
gradle.properties
sonar.gradle

Broken down `gradlew check` so that verification tasks will only run for debug variant. Full check (with other variants release, releaseMinified) will be done on release only.
SDKCF-5382

chore: improve Bitrise' builds waiting time (SDKCF-5382)

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/CampaignRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManager.kt

Cached data not loaded for anonymous user after app is restarted
SDKCF-5593

fix: opt-out status not working for "" (anonymous) users (SDKCF-5593)

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/BaseViewSpec.kt

refactor: add handling for opt-out font color when background is dark (SDKCF-5242)

---

dependency-check.gradle

This reverts commit c6879c5218d56e41bd28a08167b29ba6926d2562.
According to [this](https://github.com/jeremylong/DependencyCheck/issues/4695#issuecomment-1193634610), issue is fixed.

revert: chore: fix dependency check issue due to broken RetireJS analzer

---

bitrise.yml
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt

Test Reports add-on should be used together with Deploy to Bitrise step in order to work.
Tests can be viewed inline via the PR's Checks tab, or via Bitrise' Test Reports tab.
Also, removed unnecessary step which is deploying AAR.

chore: fix Test Reports add-on configuration for tests status display (SDKCF-5615)

---

inappmessaging/src/main/res/values-ja/strings.xml
inappmessaging/src/main/res/values/strings.xml

Fixes the warning:
`This item's android:contentDescription, "close button" contains the item type button`
Also corrected the Japanese translation.

improve: fix close button's content label accessibility warnings (SDKCF-5601)

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/EventMatchingUtil.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/EventMatchingUtilSpec.kt

When switching users, persistent campaigns list is getting cleared to show campaign for other user. 
This handling will be removed, thus making the campaign show only once throughout the app session regardless of user status.

fix: AppStart-only campaigns are re-displayed when switching users (SDKCF-6010)

---

bitrise.yml

Uses the plugin `steps-github-release` to automate Github release.
Limitation: Overriding release not yet supported (to-be): https://github.com/bitrise-steplib/steps-github-release/issues/5
In case there's a need to re-tag and a release is already published (should be a rare scenario), first delete the [release](https://github.com/rakutentech/android-inappmessaging/releases).

improve: create Github release version (SDKCF-5386)

---

build.gradle
dependency_check_suppressions.xml

https://github.com/jeremylong/DependencyCheck/issues/5220

fix: dependency check database exception caused by CVE-2020-36569

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/EventMatchingUtil.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/EventMatchingUtilSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt

When app calls `logEvent()` API (esp. on `onCreate()`), there are instances that campaign list is empty, thus failing to match the event and campaign's triggers. This PR adds handling that campaign list should be at least synced to process that event.
SDKCF-6267

fix: fix campaign is sometimes not displayed on app launch (SDKCF-6267)

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/ImpressionManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InAppMessagingConstants.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/PushPrimerTrackerManagerSpec.kt

This class is not instantiated causing low coverage , and since it does not have special implementation - can be made static (object).
SDKCF=6479

tests: increase coverage for InAppMessagingConstants (SDKCF-6479)

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageSlideUpView.kt

Removed unnecessary null check causing low coverage.
SDKCF-6478

tests: increase coverage for InAppMessageSlideUpView (SDKCF-6478)

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/DisplayMessageWorker.kt

Picasso callbacks are run on main thread, therefore when a campaign with image reaches the `onSuccess` callback and host apps cancels the campaign, preparing for next message will happen in main thread and might take long time to process, thus causing this exception.
Prepare the next message on a separate worker to fix this issue.
An addition to PR: https://github.com/rakutentech/android-inappmessaging/pull/322
SDKCF-6440

fix: `NetworkOnMainThreadException` when campaign is cancelled through contexts

---

bitrise.yml

Dependency check enabled by default, but this should be configurable because there are cases downloading from DB fails due to network issues or other issues that can take 1 or more day to resolve externally.

chore: make dependency check configurable via env variable

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageEventReconciliationWorker.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtilSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageEventReconciliationWorkerSpec.kt

Refactored to improve the testability of MessageEventReconciliationUtil by constructor DI, and added tests.
Changelog will be updated altogether in a separate PR.
SDKCF-6398

refactor: improve coverage for MessageEventReconciliationUtil (SDKCF-6398)

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/HostAppInfo.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/CampaignRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtil.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListener.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipView.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigScheduler.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationScheduler.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionScheduler.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingScheduler.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/DisplayMessageWorker.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtilSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListenerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionSchedulerSpec.kt

Refactored to improve the testability of MessageReadinessManager by constructor DI, and added tests.
Changelog will be updated altogether in a separate PR.
SDKCF-6458

refactor: improve coverage for MessageReadinessManager (SDKCF-6458)

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnable.kt

Added missing impressions handling for tooltip.
SDKCF-6547

fix: impression is not incremented when tooltip campaign is displayed (SDKCF-6547)

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/RmcHelper.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/HostAppInfo.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/ConfigQueryParamsBuilder.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/DisplayPermissionRequest.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/ImpressionRequest.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/PingRequest.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/ImpressionManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingTestConstants.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/RmcHelperSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepositorySpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/ConfigQueryParamsBuilderSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/DisplayPermissionRequestSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/ImpressionRequestSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/PingRequestSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionSchedulerSpec.kt

* Added sending of `rmcSdkVersion`:
- `/config` -> URL parameter
- `/ping`, `/display_permission`, and `/impression` -> body
N/A

feat: [RMC] add sending of `rmcSdkVersion` in IAM requests (SDKCF-6708)

---

inappmessaging/USERGUIDE.md
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingTestConstants.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/integration/IntegrationSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt

* Abort unnecessary processing when config URL is empty
N/A

improve: abort further processing/retries when config URL is empty (SDKCF-6736)

---

inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/CampaignRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepository.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipView.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigScheduler.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationScheduler.kt
inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingScheduler.kt

- Suppressed newly introduced Sonarqube issues regarding the use of singletons, as it is causing build failure
- Will re-visit these suppressions in the succeeding versions.
N/A

build: suppress new sonarqube issues

---

test/src/main/java/com/rakuten/test/AppUserInfoProvider.kt
test/src/main/java/com/rakuten/test/MainActivityFragment.kt
test/src/main/java/com/rakuten/test/MainApplication.kt
test/src/main/res/layout/fragment_main.xml
test/src/main/res/values/strings.xml

* For testing app relaunches
* Previously this was implemented in `onDestroy` but it isn't guaranteed to be called

improve: save user details in sample app cache

---

test/src/main/java/com/rakuten/test/IAMSettings.kt
test/src/main/java/com/rakuten/test/MainApplication.kt
test/src/main/java/com/rakuten/test/MainFragment.kt

For testing app relaunches with runtime configuration (sample app update only)
N/A

improve: save config settings in sample app cache (SDKCF-6887)

---

inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingTestConstants.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/integration/IntegrationSpec.kt
inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt

Backend will now throw error code 400 if appId & subsKey does not match
N/A

test: fix failing tests due to appId and subsKey mismatch

---

inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/integration/IntegrationSpec.kt

`should return valid ping response` test is failing because it validates whether campaign list is empty.
It does not make sense to check it, since campaign list can or cannot have value as it's controlled remotely.
Returning worker success is enough for this test.

test: fix integration test failure
