- .circleci/config.yml
- inappmessaging/build.gradle
- inappmessaging/proguard-rules.pro
ci/build: add publication ci, update retrofit and gson proguard settings
> ci/build: add publication ci, update retrofit and gson proguard settings

- .circleci/config.yml
- inappmessaging/build.gradle
- inappmessaging/proguard-rules.pro
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageSlideUpView.kt
- inappmessaging/src/main/res/layout/in_app_message_slide_up.xml
- inappmessaging/src/main/res/values/styles.xml
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
* removed max number of lines
* removed invisible view and changed ConstraintLayout as clickable
https://jira.rakuten-it.com/jira/browse/SDKCF-2292
> bug: [SDKCF-2292] fix slide-up layout issue for max chars

- .circleci/config.yml
- inappmessaging/build.gradle
- inappmessaging/proguard-rules.pro
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageFullScreenView.kt
- inappmessaging/src/main/res/layout/in_app_message_full_screen.xml
- inappmessaging/src/main/res/layout/in_app_message_modal.xml
- inappmessaging/src/main/res/layout/message_image_view.xml
- inappmessaging/src/main/res/layout/message_scrollview.xml
- inappmessaging/src/main/res/values/dimens.xml
- test/src/main/AndroidManifest.xml
- test/src/main/java/com/rakuten/test/MainActivity.kt
- test/src/main/java/com/rakuten/test/MainActivityFragment.kt
- test/src/main/res/layout/fragment_main.xml
- test/src/main/res/values/strings.xml
* removed unnecessary spacer
* change image and text layout to scrollview
* moved buttons in same layout of text to prevent overlap
https://jira.rakuten-it.com/jira/browse/SDKCF-2293
https://jira.rakuten-it.com/jira/browse/SDKCF-2294
https://jira.rakuten-it.com/jira/browse/SDKCF-2295
https://jira.rakuten-it.com/jira/browse/SDKCF-2296
https://jira.rakuten-it.com/jira/browse/SDKCF-2297
> bug: fix landscape mode issue not showing and overlapping texts

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ValueMatchingUtil.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ValueMatchingUtilSpec.kt
fixed calculation for LESS_THAN operator
> fix: fix `LESS_THAN` operator formula for time values

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/SharePreferencesUtil.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt
> feat: [SDKCF-3164] refactor uuid generator

- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnable.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageFullScreenView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageModalView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageSlideUpView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageView.kt
- inappmessaging/src/main/res/layout/message_image_view.xml
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/integration/IntegrationSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/ImpressionManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnableSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorkerSpec.kt
* reverted all updates for Glide
* updated to latest Fresco version
> feat: [SDKCF-3529] revert changes for Glide, and update to latest Fresco

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
> feat: updated max impression should be updated in cache

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InAppMessagingConstants.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/RetryDelayUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorkerSpec.kt
If error code 420 is encountered in Config and Ping, will retry request using exponential backoff with initial delay of 60s
> feat: add backoff delay settings for error code 429

- inappmessaging/build.gradle
- test/build.gradle
> feat: update url config to use dev environment

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ConfigResponseRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/config/ConfigResponseData.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ConfigResponseRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingSchedulerSpec.kt
- test/src/main/AndroidManifest.xml
- test/src/main/res/xml/network_security_config.xml
> feat: add roll out percentage handling

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingInitProvider.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
enable caching for this version and remove persistent data when app is relaunched
> fix: enable caching by default and fix app launch only behavior

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/api/ConfigRetrofitService.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt
- test/build.gradle
[SDKCF-3715](https://jira.rakuten-it.com/jira/browse/SDKCF-3715)
> feat: include Subscription_Id in the header of getConfig API

- inappmessaging/build.gradle
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/integration/IntegrationSpec.kt
> test: enable integration spec

- Gemfile
- Gemfile.lock
- _config.yml
- docs/3.0/index.md
> docs: fix documentation format for Troubleshooting

- Gemfile
- Gemfile.lock
- _config.yml
- docs/3.0/index.md
> docs: update target and compile SDK version to be 30 or above

- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListenerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt
Disabled intermittent test cases to avoid failing PRs for now.
Will look into this after all feature implementation.
> test: disable intermittent test cases

- .github/pull_request_template.md
> docs: add additional checklist items to PR template

- inappmessaging/USERGUIDE.md
> docs: [SDKCF-3939] add recommendation to use remote feature flag

- build.gradle
- inappmessaging/USERGUIDE.md
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/BaseTest.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt
- test/build.gradle
> feat: update minimum SDK to API 23

- inappmessaging/src/main/res/layout/close_button.xml
- inappmessaging/src/main/res/layout/in_app_message_modal.xml
- inappmessaging/src/main/res/values/dimens.xml
- inappmessaging/src/main/res/values/styles.xml
> refactor: increase the clickable area of the IAM close button "x"

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
> feat: add instance reset on failed initialization

- inappmessaging/src/main/res/layout/message_scrollview.xml
> fix: change modal and fullscreen header text alignment to center

- build.gradle
- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ConfigResponseRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/EventsManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnableSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentServiceSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtilSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/RuntimeUtilSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtilSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/BaseViewSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListenerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageEventReconciliationWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorkerSpec.kt
> feat: [SDKCF-4196][SDKCF-4190] remove jcenter dependency and update kluent version

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/UserInfoProvider.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/api/MessageMixerRetrofitService.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/enums/UserIdentifierType.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/RuntimeUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/TestUserInfoProvider.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/api/MessageMixerRetrofitServiceSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/integration/IntegrationSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/RuntimeUtilSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorkerSpec.kt
- test/src/main/java/com/rakuten/test/AppUserInfoProvider.kt
- test/src/main/java/com/rakuten/test/MainActivityFragment.kt
- test/src/main/res/layout/dialog_users.xml
- test/src/main/res/values/strings.xml
> feat: [SDKCF-4151] remove rakutenId in UserInfoProvider and renamed to provideAccessToken

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/messages/Message.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/CampaignData.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/MessageMixerResponseSpec.kt
> feat: make trigger optional (for test campaigns)

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/appevents/CustomEvent.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/appevents/CustomEventSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtilSpec.kt
> fix: [SDKCF-4530] add handling for case-sensitivity changes in custom event

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
> fix: add setting of campaign id to view tag

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/CacheUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/WorkerUtils.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/BaseTest.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorkerSpec.kt
> improve: update handling for different response code for config, ping, and impression request (SDKCF-4636)

- .sonarcloud.properties
To avoid analysis on test code
> ci: add sonarcloud config to focus analysis on source code

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageJobIntentService.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ValueMatchingUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ValueMatchingUtilSpec.kt
> refactor: fix code smells and vulnerabilities reported in sonarcloud (SDKCF-4717)

- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/WorkerUtils.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
> feat: add error handling for display permission request (SDKCF-4729)

- bitrise.yml
- build.gradle
- sonar.gradle
Integrate to SonarQube.
No master data yet in SonarQube.
It will be populated when these changes are merged to master.
(We will also be able to test PR data once merged to master.)
Sample build using other branch:
https://app.bitrise.io/build/851a3cd1-fd0b-4094-a17c-1c315fa5a40c#?tab=log
SDKCF-4694
> ci: integrate to SonarQube (SDKCF-4694)

- bitrise.yml
> ci: add Danger integration (SDKCF-4739)

- bitrise.yml
Moved back bitrise.yml from `bitrise` branch to alongside source code files.
Modified bitrise wrapper config to control which bitrise.yml to use.
It can support bitrise.yml builds from branch or forked repo by opening a PR, for easier validation of bitrise.yml plus any change in source files (e.g. sonar.gradle).
See inline comments 
https://app.bitrise.io/app/e9cc83da00ffd2b1/workflow_editor#!/yml
SDKCF-4838
> ci: improve bitrise config testing

- inappmessaging/src/main/res/layout/message_scrollview.xml
> fix: add center gravity for campaign body (SDKCF-4835)

- build.gradle
- dependency-check.gradle
- sonar.gradle
> ci: add dependency checking to CI pipeline (SDKCF-4820)

- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnable.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipView.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtilSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipViewSpec.kt
> fix: add correct handling for tooltip position for sample app

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/WorkerUtils.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/BaseTest.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorkerSpec.kt
- test/src/main/java/com/rakuten/test/MainApplication.kt
> feat: update public API to align with iOS (SDKCF-4941)

- inappmessaging/build.gradle
> fix: update sdk utils to latest released version

- analytics/build.gradle
- build.gradle
- inappmessaging/build.gradle
- test/build.gradle
> feat: apply Gitleaks plugin to IAM SDK (SDKCF-2623)

- analytics/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- test-compose/build.gradle
- test/build.gradle
> feat: Support for building with Java 11 (SDKCF-4919)

- analytics/build.gradle
- bitrise.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- test-compose/build.gradle
- test/build.gradle
Moved to the next release to complete testing using the Ecosystem Demo app (with Java 11)
> Revert "feat: Support for building with Java 11 (SDKCF-4919)"

- detekt-config.yml
- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/models/appevents/BaseEvent.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ConfigResponseRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/RuntimeUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListener.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/DisplayMessageWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListenerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorkerSpec.kt
> refactor: update to a stricter detekt check (SDKCF-5173)

- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
> refactor: update SDK utils to release version (SDKCF-5295)

- sonar.gradle
> ci: update sonarqube's vulnerabilities severity score

- bitrise.yml
- build.gradle
- test-compose/build.gradle
- test/build.gradle
> poc: add emerge tool setup

- bitrise.yml
- sonar.gradle
Before merging:
* Update the Bitrise Web UI trigger to match this update's `trigger_map`
> chore: Sonarqube for release/* branch (SDKCF-5381)

- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/EventTrackerHelper.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalDisplayedMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalEventRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/LocalOptedOutMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/PingResponseMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/ReadyForDisplayMessageRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/ImpressionManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InAppLogger.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/RuntimeUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/WorkerUtils.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ConfigWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/DisplayMessageWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageEventReconciliationWorker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepositorySpec.kt
> feat: update SDK Utils to v2.0.0 and add logger class (SDKCF-5510)

- dependency_check_suppressions.xml
Temporarily suppress dependency check issue for failing CI builds
> chore: suppress dependency check issue

- build.gradle
- dependency_check_suppressions.xml
- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt
- test-compose/build.gradle
- test/build.gradle
> feat: add Android 13 support (SDKCF-5778)

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtil.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/MessageEventReconciliationUtilSpec.kt
> improve: validate triggers for test campaigns (SDKCF-5777)

- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/runnable/DisplayMessageRunnable.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ViewUtil.kt
This is to fix scroll view issue when using CoordinatorLayout as main container of target UI.
> fix: add special handling for coordinator layout

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/enums/ButtonActionType.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/enums/CampaignType.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/requests/PingRequest.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/BuildVersionChecker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/enums/ButtonActionTypeSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/enums/CampaignTypeSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorkerSpec.kt
> feat: add push primer handling (SDKCF-5565)

- build.gradle
- dependency_check_suppressions.xml
- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/CampaignRepository.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ImageUtil.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepositorySpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/SessionManagerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ImpressionSchedulerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorkerSpec.kt
> refactor: update dependencies to remove vulnerabilities (SDKCF-5835)

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
- inappmessaging/src/main/res/values-v33/styles.xml
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/BaseViewSpec.kt
> improve: add campaign UX Improvements related to texts' wrapping for readability (SDKCF-5893)

- README.md
- dependency-check.gradle
- test-compose/build.gradle
- test/build.gradle
> chore: update to be able to execute `gradlew check` (SDKCF-5952)

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManager.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/MessageReadinessManagerSpec.kt
> bug: fix issue on campaign not displayed after going to background (SDKCF-6009)

- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessaging.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/PushPrimerTrackerManager.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InAppMessagingConstants.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/PushPrimerTrackerManagerSpec.kt
> feat: add Push Primer opt-in tracking (SDKCF-6025)

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManager.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/manager/DisplayManagerSpec.kt
Handler processing is still executed even after tooltip has been manually closed by user using [X] button.
Added handling to first check if tooltip is still visible.
> fix: impressions handling is duplicated for tooltip with auto disappear delay (SDKCF-6056)

- bitrise.yml
See [releases](https://github.com/rakutentech/android-inappmessaging/releases) for sample output.
> improve: update Github release body to userguide content

- .github/CODEOWNERS
> chore: update code owners list

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepository.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/InAppMessagingSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/AccountRepositorySpec.kt
> fix: campaign being displayed multiple times when upgrading to version `7.2.0` or later (SDKCF-6391)

- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageEventReconciliationWorkerSpec.kt
Updated MessageEventReconciliationWorker test to increase coverage.
N/A
> tests: update tests for MessageEventReconciliationWorker

- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/service/DisplayMessageWorkerSpec.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/InitializerSpec.kt
Added tests for Initializer to increase coverage.
Since there is no change in source file, did not add new entry in changelog.
SDKCF-6401
> tests: update tests for Initializer (SDKCF-6401)

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipView.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessagingTooltipViewSpec.kt
Removed repetitive LOC causing low coverage, and added tests.
Will update the changelog altogether in a separate PR.
SDKCF-6438
> tests: increase coverage for InAppMessagingTooltipView (SDKCF-6438)

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/TriggerAttributesValidator.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/TriggerAttributesValidatorSpec.kt
Added tests.
Will update the changelog altogether in a separate PR.
SDKCF-6399
> tests: increase coverage for TriggerAttributesValidator (SDKCF-6399)

- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ValueMatchingUtilSpec.kt
Added tests.
No need to add change in changelog since this is tests-only update.
SDKCF-6484
> tests: increase coverage for ValueMatchingUtil (SDKCF-6484)

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseViewSpec.kt
Removed unnecessary null checks causing low coverage, and added tests.
Will update changelog altogether in a separate PR.
SDKCF-6486
> tests: increase coverage in InAppMessageBaseView (SDKCF-6486)

- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/repositories/HostAppInfoRepositorySpec.kt
> tests: increase coverage in HostAppInfoRepository (SDKCF-6490)

- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutineSpec.kt
> tests: increase coverage for MessageActionsCoroutine (SDKCF-6402)

- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/data/responses/ping/MessageSpec.kt
Added tests.
No need to add in changelog.
N/A
> tests: increase coverage for Message

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListener.kt
Removed unnecessary null checks
Will update changelog altogether in a separate PR.
N/A
> refactor: increase coverage for InAppMessageViewListener

- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/InApp.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/coroutine/MessageActionsCoroutine.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/BuildVersionChecker.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/Initializer.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/ResourceUtils.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageBaseView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageViewListener.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/MessageMixerWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/BuildVersionCheckerSpec.kt
Removed boilerplate code and added tests.
Will update changelog altogether in a separate PR.
SDKCF-6513
> refactor: improve coverage in BuildVersionChecker (SDKCF-6513)

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/api/ConfigRetrofitService.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageView.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/ConfigScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/EventMessageReconciliationScheduler.kt
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/schedulers/MessageMixerPingScheduler.kt
- Fixes SonarCloud code smells [kotlin:S6517](https://sonarcloud.io/organizations/rakutentech/rules?open=kotlin%3AS6517&rule_key=kotlin%3AS6517&tab=why).
- Interface methods with default values cannot be made functional interface, suppressed it for now.
SDKCF-6518
> improve: fixed and suppressed some SonarCloud code smells (SDKCF-6518)

- build.gradle
- dependency_check_suppressions.xml
- inappmessaging/USERGUIDE.md
- inappmessaging/build.gradle
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/utils/BuildVersionCheckerSpec.kt
- test-compose/build.gradle
Up to minor version upgrade to some libraries, mostly quality tools. And updated next suppression date limit.
SDKCF-6596
> improve: removed some dependency check suppression by upgrading libraries (SDKCF-6596)

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageModalView.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/view/InAppMessageModalViewSpec.kt
> tests: improve coverage of InAppMessageModalView.kt (SDKCF-6611)

- inappmessaging/USERGUIDE.md
- inappmessaging/src/main/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorker.kt
- inappmessaging/src/test/java/com/rakuten/tech/mobile/inappmessaging/runtime/workmanager/workers/ImpressionWorkerSpec.kt
- Added tests
- Made test class simpler by making use of `MockWebServer` and `TestWorkerBuilder`
SDKCF-6613
> tests: improve coverage of ImpressionWorker.kt (SDKCF-66113)

- inappmessaging/USERGUIDE.md
Documentation update:
- Add sections
- Re-arrange steps
- User targeting (specify user info in table form, migration/impact note)
- Removed PushPrimer
- Caution when using AppStart-only
- FAQ (for versionCode)
- Final code (sample)
> docs: improve Userguide (RMCCX-6695)

- dependency_check_suppressions.xml
- inappmessaging/USERGUIDE.md
Describe the changes in this pull request.
Explain your rationale of technical decisions you made (unless discussed before).
Add public links to github issues, design documents and other relevant resources (e.g. previous discussions, platform/tool documentation etc.)
> docs: add SDK logic for deeplink handling (RMCCX-9127)

- bitrise.yml
Describe the changes in this pull request.
Explain your rationale of technical decisions you made (unless discussed before).
Add public links to github issues, design documents and other relevant resources (e.g. previous discussions, platform/tool documentation etc.)
> ci: add option to run or skip Dependency check tool
